server:
  port: 8001

spring:
  application:
    name: order-my-food
  data:
    mongodb:
      auto-index-creation: true
  zipkin:
    enabled: true

logging:
  file:
    name: D:/201/OrderMyFood/restaurant-search-service/ordermyfood.log
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"